//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Estdat.rc
//
#define IDC_MYICON                      2
#define REPOSITORIO                     2
#define IDD_SUBIR_IMAGEN                3
#define IDD_ESTDAT_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_ESTDAT                      107
#define IDI_SMALL                       108
#define IDC_ESTDAT                      109
#define IDR_MAINFRAME                   128
#define IDD_INICIO                      129
#define IDD_Menu                        130
#define IDD_VUELO_REGISTRO              132
#define IDD_DIALOG3                     133
#define IDD_PASAJEROS_REGISTRO          134
#define IDR_MENU1                       134
#define IDD_BOLETOS_REGISTRO            135
#define IDD_DIALOG2                     136
#define IDD_VUELO_MODIFICAR             137
#define IDD_VUELO_ELIMINAR              138
#define IDD_PASAJEROS_ELIMINAR          139
#define IDD_PASAJEROS_MODIFICAR         140
#define IDD_BOLETOS_ELIMINAR            141
#define IDD_PASAJEROS_MODIFICAR1        142
#define IDD_BOLETOS_MODIFICAR           142
#define IDD_USUARIO                     143
#define IDD_PASE_ABORDAR                144
#define IDD_MANIFIESTO_NUMERO           145
#define IDD_MANIFIESTO_NOMBRE           146
#define IDD_MANIFIESTO_APELLIDO         147
#define ID_iniciarSesion                1000
#define IDC_EDIT1                       1002
#define IDD_crearUsuario                1003
#define IDC_EDIT3                       1003
#define IDC_EDIT2                       1004
#define IDC_DATETIMEPICKER1             1004
#define IDC_EDIT8                       1004
#define IDC_CONTRASENA                  1004
#define IDC_DATETIMEPICKER2             1005
#define IDC_EDIT6                       1005
#define IDC_fechaLlegada                1005
#define IDC_EDIT4                       1006
#define IDC_EDIT7                       1006
#define IDC_DATETIMEPICKER3             1006
#define IDC_FECHA_LLEGADA               1006
#define IDC_COMBO1                      1007
#define IDC_EDIT9                       1007
#define IDC_tipoAvion                   1007
#define IDC_EDIT5                       1008
#define IDC_EDIT_HORA_SALIDA            1008
#define IDC_COMBO2                      1009
#define IDC_claseAvion                  1009
#define IDC_EDIT10                      1009
#define IDC_EDIT_HORA_LLEGADA           1009
#define IDC_DATETIMEPICKER5             1010
#define IDC_horaSalida                  1010
#define IDC_LIST1                       1011
#define IDC_horaLlegada                 1011
#define IDC_DATETIMEPICKER4             1013
#define IDC_USUARIO                     1014
#define IDC_CORREO                      1015
#define IDC_NOMBRE                      1016
#define IDC_GENERO                      1017
#define IDC_vueloOrigen                 1018
#define IDC_vueloDestino                1019
#define IDC_fechaSalida                 1020
#define IDC_asientosDisponibles         1021
#define IDC_idVuelo                     1022
#define IDC_vuelos                      1023
#define IDC_CHECK_RECORDAR              1024
#define IDC_LIST_VUELO_ELIMINAR         1025
#define IDC_EDIT_VUELOS_ORIGEN          1026
#define IDC_EDIT_VUELOS_DESTINO         1027
#define IDC_FECHA_SALIDA                1028
#define ID_VUELOS_REGISTRARVUELO        32771
#define ID_VUELOS_ELIMINARVUELO         32772
#define ID_VUELOS_MODIFICARVUELO        32773
#define ID_PASAJEROS_REGISTRARPASAJEROS 32774
#define ID_PASAJEROS_ELIMINARPASAJEROS  32775
#define ID_PASAJEROS_MODIFICARPASAJEROS 32776
#define ID_BOLETOS_COMPRARBOLETOS       32777
#define ID_BOLETOS_CANCELARBOLETOS      32778
#define ID_M32779                       32779
#define ID_M32780                       32780
#define ID_FUNCINESEXCLUSIVASDEADMIN_REGISTRARUSUARIOS 32781
#define ID_BOLETOS_MODIFICARBOLETOS     32782
#define ID_M                            32783
#define ID_MISC_PASEDEABORDAR           32784
#define ID_ADMIN_REGISTRARUSUARIOS      32785
#define ID_M32786                       32786
#define ID_MANIFIESTO_ORDENAR           32787
#define ID_MANIFIESTO_ORDENARPORN32788  32788
#define ID_M32789                       32789
#define ID_VERMANIFIESTO_VERPORN32790   32790
#define ID_VERMANIFIESTO_VERPORNOMBRE   32791
#define ID_VERMANIFIESTO_VERPORAPELLIDO 32792
#define ID_VERMANIFIESTO_VERPORNUMERO   32793
#define ID_VERMANIFIESTO_VERPORNUMERODEASIENTP 32794
#define ID_VERMANIFIESTO_VERPORNUMERODEASIENTO 32795
#define ID_M32796                       32796
#define ID_SALIR_NOGURDAR               32797
#define ID_FUNCINESEXCLUSIVASDEADMIN_REINICIARIDSDEVUELOS 32798
#define ID_M32799                       32799
#define ID_OTRASOPCIONES_REPARARUSUARIO 32800
#define ID_OTRASOPCIONES_REPARARUSUARIO32801 32801
#define ID_ADMIN_REINICIARIDSDEVUELOS   32802
#define ID_OTRASOPCIONES_REPARAR_ADMIN  32803
#define ID_M32804                       32804
#define ID_REPARAR_USUARIO              32805
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
